version: "3.4"
services:
    nginx:
        image: nginx:1.23.3
        container_name: nginx
        volumes:
            - ./services/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
            - ./services/nginx/challenge/:/var/www/certbot/:ro
            - ./services/nginx/certs/:/etc/nginx/ssl/:ro
            - ./logs/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped

    typesense:
        image: typesense/typesense:26.0
        container_name: typesense
        volumes:
            - ./logs/:/logs/
            - ./data:/data
            - ./backups:/backups
        environment:
            - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
            - TYPESENSE_API_PORT=${TYPESENSE_API_PORT}
            - TYPESENSE_DATA_DIR=${TYPESENSE_DATA_DIR}
            - TYPESENSE_LOG_DIR=${TYPESENSE_LOG_DIR}
            - TYPESENSE_ENABLE_CORS=${TYPESENSE_ENABLE_CORS}
        ports:
            - "8443:8443"
        restart: unless-stopped
